### ISSUE TITLE
Compatibility with PHP 7

### ISSUE THREAD

**Issue by safrazik** [adrotec/odataphpprod#1]
_From @popovsergiy on February 12, 2017 12:6_

This is not to `breeze.server.php` but to [your fork of odataphpprod](https://github.com/adrotec/odataphpprod) (that fork not has *Issues* tab).

I get next error when try run code on the PHP 7
`Fatal error: Cannot use ODataProducer\Providers\Metadata\Type\String as String because 'String' is a special class name in vendor\adrotec\odataphpprod\library\ODataProducer\Providers\Metadata\ResourceType.php on line 47`
Can this will be fixed?

_Copied from original issue: adrotec/breeze.server.php#26_

**Comment by safrazik** [comment]
working on it

**Comment by kingschnulli** [comment]
Any progress here?

**Comment by safrazik** [comment]
Just landed in version [`1.1.0`](https://github.com/adrotec/odataphpprod/releases/tag/1.1.0) from [`this commit`](https://github.com/adrotec/odataphpprod/commit/235086d31b9cadd1c92fb98ba8a99a10847fe0b1)

**Comment by safrazik** [comment]
Update [`breeze.server.php`](https://github.com/adrotec/breeze.server.php) library to version [`1.1.0`](https://github.com/adrotec/breeze.server.php/releases/tag/1.1.0)
